### ISSUE TITLE
FR Node Explorer: toggle visibility of dotfiles

### ISSUE THREAD

**Issue by thisisparker** [tailscale-dev/vscode-tailscale#199]
My `~` directory has a lot of hidden files and directories for configuration that I would like to hide unless I need them. Ideally there's a setting and keyboard shortcut to show/hide these entries either globally or on a per-node basis. (I expect that to be `ctrl+H` and hit it by default, fwiw.)

**Comment by samlinville** [comment]
@tendstofortytwo work here is done, but can you review the PR?
