### ISSUE TITLE
Command to open Tailscale node in remote

### ISSUE THREAD

**Issue by tylersmalley** [tailscale-dev/vscode-tailscale#217]
While we can't add to the existing Remote SSH list, we can create a command that does something similar. Open a list of all Tailscale nodes that possibly have SSH enabled. Looks like we can separate these based on if they are reported to be online or not.

**Comment by tendstofortytwo** [comment]
fwiw, at least on Linux the existing remote SSH list seems to refer to `~/.ssh/config`, which in theory could be modified to add nodes. I would guess it's the same for macOS, but not sure about Windows. Not sure if that's something we want to do though?
