### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by emilytrau** [tailscale-dev/vscode-tailscale#3]
It would be great to have this published to [Open VSX](https://open-vsx.org/) as well so it can be used with open-source vscode distributions!

**Comment by emilytrau** [comment]
@tylersmalley I use openvscode-server 😊

**Comment by tendstofortytwo** [comment]
Tailscale is now available on Open VSX! https://open-vsx.org/extension/tailscale/vscode-tailscale
