### ISSUE TITLE
Install Tailscale flow for new users

### ISSUE THREAD

**Issue by samlinville** [tailscale-dev/vscode-tailscale#31]
When Tailscale isn't installed, we should offer a very fast and easy way to install it on a user's machine. This should be an OS-specific recommendation.

As a user I can:

- Click a button to begin the installation process, regardless of OS
  - macOS: Open App Store page
  - Windows: Open and start .exe download
  - Linux: Open new terminal panel and run our curl | sh download script
- Instead, opt to click a link or button to go https://tailscale.com/download if I prefer to manage the download process myself.

**Comment by tylersmalley** [comment]
This is completed.
